project_name: salt-updater

release:
  github:
    owner: TheCacophonyProject
    name: salt-updater
  name_template: '{{.Tag}}'

builds:
- goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
  main: ./cmd/salt-updater
  ldflags: -s -w -X main.version={{.Version}}
  binary: salt-updater

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Controls the salt updates
  license: GPL v3.0
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  files:
    "_release/salt-updater.service": "/etc/systemd/system/salt-updater.service"
    "_release/org.cacophony.salt-updater.conf": "/etc/dbus-1/system.d/org.cacophony.salt-updater.conf"
  scripts:
        postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
